import enum

class CSVColumnNames(enum.Enum):
    YEARSTART = 'YearStart'
    YEAREND = 'YearEnd'
    LOCATIONABBR = 'LocationAbbr'
    LOCATIONDESC = 'LocationDesc'
    DATASOURCE = 'Datasource'
    CLASS = 'Class'
    TOPIC = 'Topic'
    QUESTION = 'Question'
    DATA_VALUE_UNIT = 'Data_Value_Unit'
    DATA_VALUE_TYPE = 'Data_Value_Type'
    DATA_VALUE = 'Data_Value'
    DATA_VALUE_ALT = 'Data_Value_Alt'
    DATA_VALUE_FOOTNOTE_SYMBOL = 'Data_Value_Footnote_Symbol'
    DATA_VALUE_FOOTNOTE = 'Data_Value_Footnote'
    LOW_CONFIDENCE_LIMIT = 'Low_Confidence_Limit'
    HIGH_CONFIDENCE_LIMIT = 'High_Confidence_Limit '
    SAMPLE_SIZE = 'Sample_Size'
    TOTAL = 'Total'
    AGE = 'Age(years)'
    EDUCATION = 'Education'
    GENDER = 'Gender'
    INCOME = 'Income'
    RACE_ETHNICITY = 'Race/Ethnicity'
    GEOLOCATION = 'GeoLocation'
    CLASSID = 'ClassID'
    TOPICID = 'TopicID'
    QUESTIONID = 'QuestionID'
    DATAVALUETYPEID = 'DataValueTypeID'
    LOCATIONID = 'LocationID'
    STRATIFICATIONCATEGORY1 = 'StratificationCategory1'
    STRATIFICATION1 = 'Stratification1'
    STRATIFICATIONCATEGORYID1 = 'StratificationCategoryId1'
    STRATIFICATIONID1 = 'StratificationID1'
